#include "models\ReferenceDcMotor.hpp"
#include "models\DcMotor.hpp"
#include "models\Pendulum.hpp"
#include "models\DoublePendulum.hpp"
#include "models\SeriesRLC.hpp"

#include "algorithms\NeuralNetwork.hpp"
#include "algorithms\NeuralRegulator.hpp"
#include "algorithms\EvolutionaryAlgorithm.hpp"
#include "algorithms\Pid.hpp" 
#include "algorithms\Noise.hpp"
#include "algorithms\Filter.hpp"
